### ISSUE TITLE
Implement fire logic for missing events.

### ISSUE THREAD

**Issue by x7airworker** [OnfireNetwork/OnsetJava#1]
The following events have to be implemented:
[**Server events**](https://dev.playonset.com/wiki/Template:ServerEvents)
- [x] OnPlayerPickupHit
- [x] OnVehiclePickupHit
- [x] OnPlayerStreamIn
- [x] OnPlayerStreamOut
- [x] OnPlayerJoin
- [x] OnPlayerQuit
- [x] OnPlayerSpawn
- [x] OnPlayerDeath
- [x] OnPlayerWeaponShot
- [x] OnPlayerDamage
- [x] OnPlayerChat
- [x] OnPlayerChatCommand
- [x] OnPlayerEnterVehicle
- [x] OnPlayerLeaveVehicle
- [x] OnPlayerStateChange
- [x] OnVehicleRespawn
- [x] OnVehicleStreamIn
- [x] OnVehicleStreamOut
- [x] OnClientConnectionRequest
- [x] OnPlayerServerAuth
- [x] OnPlayerSteamAuth
- [x] OnPlayerDownloadFile
- [x] OnNPCReachTarget
- [x] OnNPCDamage
- [x] OnNPCSpawn
- [x] OnNPCDeath

[**Client events**](https://dev.playonset.com/wiki/Template:ClientEvents)
- [x] OnCollisionEnter
- [x] OnCollisionLeave
- [x] OnResolutionChange
- [x] OnPlayerCrouch
- [x] OnPlayerEndCrouch
- [x] OnPlayerEndFall
- [x] OnPlayerFall
- [x] OnPlayerEnterWater
- [x] OnPlayerLeaveWater
- [x] OnPlayerReloaded
- [x] OnPlayerParachuteLand
- [x] OnPlayerSkydiveCrash
- [x] OnPlayerCancelSkydive
- [x] OnPlayerSkydive
- [x] OnPlayerParachuteOpen
- [x] OnPlayerParachuteClose
- [x] OnObjectHit
- [x] OnPlayerEndEditObject
- [x] OnPlayerBeginEditObject
- [x] OnKeyPress
- [x] OnKeyRelease
- [x] OnLightStreamIn
- [x] OnNPCStreamIn
- [x] OnObjectStreamIn
- [x] OnPickupStreamIn
- [x] OnSoundFinished
- [x] OnText3DStreamIn
- [x] OnWebLoadComplete

### Won't implement on client side, because same events are existing on the server side.
- OnPlayerDeath
- OnPlayerEnterVehicle
- OnPlayerLeaveVehicle
- OnPlayerChatCommand
- OnPlayerChat
- OnPlayerSpawn
- OnPlayerWeaponShot
- OnVehicleStreamOut
- OnVehicleStreamIn
- OnPlayerStreamIn
- OnPlayerStreamOut

**Comment by JanHolger** [comment]
Finished
