### ISSUE TITLE
Implement missing functions for server.

### ISSUE THREAD

**Issue by x7airworker** [OnfireNetwork/OnsetJava#9]
The following functions have to be implemented:

[**Server functions**](https://dev.playonset.com/wiki/Template:ServerFunctions)

- [x] GetTickCount
- [x] GetGameVersion
- [x] GetGameVersionString
- [x] GetServerTickRate
- [x] ServerExit
- [x] SetServerName
- [x] GetServerName
- [x] GetMaxPlayers
- [x] CreateExplosion
- [x] CreateLight
- [x] DestroyLight
- [x] GetNetworkStats
- [x] CreateNPC
- [x] DestroyNPC
- [x] IsNPCStreamedIn
- [x] GetNPCModel
- [x] SetNPCLocation
- [x] GetNPCLocation
- [x] SetNPCHealth
- [x] GetNPCHealth
- [x] SetNPCAnimation
- [x] SetNPCHeading
- [x] GetNPCHeading
- [x] SetNPCTargetLocation
- [x] SetNPCFollowPlayer
- [x] SetNPCFollowVehicle
- [x] CreateObject
- [x] DestroyObject
- [x] GetObjectModel
- [x] IsObjectStreamedIn
- [x] SetObjectStreamDistance
- [x] SetObjectLocation
- [x] GetObjectLocation
- [x] SetObjectRotation
- [x] GetObjectRotation
- [x] SetObjectScale
- [x] GetObjectScale
- [x] SetObjectAttached
- [x] SetObjectDetached
- [x] IsObjectAttached
- [x] GetObjectAttachmentInfo
- [x] IsObjectMoving
- [x] SetObjectMoveTo
- [x] StopObjectMove
- [x] SetObjectRotateAxis
- [x] SetObjectColor
- [x] SetObjectTexture
- [x] SetObjectAnimatedTexture
- [x] CreatePickup
- [x] DestroyPickup
- [x] SetPickupScale
- [x] GetPickupScale
- [x] GetStreamedPlayersForPlayer
- [x] SetPlayerName
- [x] GetPlayerName
- [x] GetPlayerSteamId
- [x] GetPlayerNetworkStats
- [x] SetPlayerSpawnLocation
- [x] IsPlayerStreamedIn
- [x] SetPlayerVoiceEnabled
- [x] IsPlayerVoiceEnabled
- [x] IsPlayerTalking
- [x] AddPlayerChat
- [x] AddPlayerChatRange
- [x] GetPlayerState
- [x] GetPlayerMovementMode
- [x] GetPlayerMovementSpeed
- [x] IsPlayerAiming
- [x] IsPlayerReloading
- [x] GetPlayerVehicle
- [x] GetPlayerVehicleSeat
- [x] SetPlayerInVehicle
- [x] RemovePlayerFromVehicle
- [x] SetPlayerLocation
- [x] GetPlayerLocation
- [x] SetPlayerWeaponStat
- [x] SetPlayerWeapon
- [x] GetPlayerWeapon
- [x] GetPlayerEquippedWeaponSlot
- [x] EquipPlayerWeaponSlot
- [x] GetPlayerEquippedWeapon
- [x] SetPlayerHeading
- [x] GetPlayerHeading
- [x] SetPlayerSpectate
- [x] ResetPlayerCamera
- [x] IsPlayerDead
- [x] SetPlayerHealth
- [x] GetPlayerHealth
- [x] SetPlayerArmor
- [x] GetPlayerArmor
- [x] SetPlayerRespawnTime
- [x] GetPlayerRespawnTime
- [x] SetPlayerModel
- [x] GetPlayerModel
- [x] GetPlayerIP
- [x] GetPlayerPing
- [x] KickPlayer
- [x] GetPlayerLocale
- [x] GetPlayerGUID
- [x] SetPlayerAnimation
- [x] AttachPlayerParachute
- [x] SetPlayerHeadSize
- [x] GetPlayerHeadSize
- [x] CreateText3D
- [x] DestroyText3D
- [x] SetText3DAttached
- [x] GetVehicleModel
- [x] GetVehicleModelName
- [x] SetVehicleRespawnParams
- [x] IsVehicleStreamedIn
- [x] GetStreamedVehiclesForPlayer
- [x] SetVehicleLocation
- [x] GetVehicleLocation
- [x] SetVehicleRotation
- [x] GetVehicleRotation
- [x] SetVehicleHeading
- [x] GetVehicleHeading
- [x] SetVehicleHealth
- [x] GetVehicleHealth
- [x] SetVehicleLicensePlate
- [x] GetVehicleVelocity
- [x] CreateVehicle
- [x] DestroyVehicle
- [x] GetVehicleDriver
- [x] GetVehiclePassenger
- [x] GetVehicleNumberOfSeats
- [x] SetVehicleColor
- [x] GetVehicleColor
- [x] GetVehicleInteriorColor
- [x] SetVehicleLinearVelocity
- [x] SetVehicleAngularVelocity
- [x] GetVehicleGear
- [x] SetVehicleHoodRatio
- [x] GetVehicleHoodRatio
- [x] SetVehicleTrunkRatio
- [x] GetVehicleTrunkRatio
- [x] StartVehicleEngine
- [x] StopVehicleEngine
- [x] GetVehicleEngineState
- [x] SetVehicleLightEnabled
- [x] GetVehicleLightState
- [x] GetVehicleLightColor
- [x] SetVehicleDamage
- [x] GetVehicleDamage
- [x] AttachVehicleNitro
- [x] SetPlayerDimension
- [x] SetVehicleDimension
- [x] SetObjectDimension
- [x] SetLightDimension
- [x] SetPickupDimension
- [x] SetText3DDimension
- [x] SetNPCDimension

**Comment by x7airworker** [comment]
Done what I could(163029d2308a738b4614bc9049a46c75ed34e4e2), more investigation into definition of the functions is needed.

**Comment by JanHolger** [comment]
Done with commit 49fd680a00094bf708cc848b842f556e726d0c63
